# Generated by Django 5.1.15 on 2026-09-27 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('beneficiaries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='assessed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessment',
            name='beneficiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='beneficiaries.beneficiary'),
        ),
        migrations.AddField(
            model_name='assessmentfactor',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factors', to='assessments.assessment'),
        ),
        migrations.AddField(
            model_name='rule',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rule',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentfactor',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.rule'),
        ),
        migrations.AddField(
            model_name='rule',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.rulecategory'),
        ),
    ]
