import React, { useEffect, useState } from 'react';
import PageHeader from '../../components/common/PageHeader';
import DataTable from '../../components/common/DataTable';
import Badge from '../../components/common/Badge';
import Modal from '../../components/common/Modal';
import FileUpload from '../../components/forms/FileUpload';
import FormSelect from '../../components/forms/FormSelect';
import { beneficiaryAPI, documentAPI } from '../../services/api';
import { CheckCircle, XCircle, UploadCloud } from 'lucide-react';

const documentTypes = [
  { value: 'INCOME_PROOF', label: 'Income Proof' },
  { value: 'RATION_CARD', label: 'Ration Card' },
  { value: 'BIRTH_CERTIFICATE', label: 'Birth Certificate' },
  { value: 'SCHOOL_CERTIFICATE', label: 'School Certificate' },
  { value: 'BONAFIDE', label: 'Bonafide' },
  { value: 'MARKSHEET', label: 'Marksheet' },
  { value: 'OTHER', label: 'Other' },
];

export default function DocumentVerification() {
  const [documents, setDocuments] = useState([]); const [beneficiaries, setBeneficiaries] = useState([]); const [selected, setSelected] = useState(null); const [reason, setReason] = useState(''); const [file, setFile] = useState(null); const [beneficiary, setBeneficiary] = useState(''); const [documentType, setDocumentType] = useState('INCOME_PROOF'); const [uploadError, setUploadError] = useState(''); const [loading, setLoading] = useState(true); const [uploading, setUploading] = useState(false); const [error, setError] = useState('');
  const load = () => documentAPI.list().then(setDocuments).catch(apiError => setError(apiError.message || 'Unable to load documents.')).finally(() => setLoading(false));
  useEffect(() => { load(); beneficiaryAPI.list().then(setBeneficiaries).catch(apiError => setError(apiError.message || 'Unable to load beneficiaries.')); }, []);
  const selectFile = nextFile => { setUploadError(''); if (!nextFile) { setFile(null); return; } const allowed = ['application/pdf', 'image/jpeg', 'image/png']; if (!allowed.includes(nextFile.type)) { setUploadError('Choose a PDF, JPG, or PNG file.'); return; } if (nextFile.size > 10 * 1024 * 1024) { setUploadError('File must be smaller than 10 MB.'); return; } setFile(nextFile); };
  const upload = async event => { event.preventDefault(); if (!beneficiary || !file) { setUploadError('Select a beneficiary and file before uploading.'); return; } setUploading(true); setUploadError(''); const body = new FormData(); body.append('beneficiary', beneficiary); body.append('document_type', documentType); body.append('file', file); body.append('file_name', file.name); try { await documentAPI.upload(body); setFile(null); setBeneficiary(''); await load(); } catch (apiError) { setUploadError(apiError.message || 'Unable to upload document.'); } finally { setUploading(false); } };
  const verify = async id => { try { await documentAPI.verify(id); await load(); } catch (apiError) { setError(apiError.message || 'Unable to verify document.'); } };
  const reject = async () => { try { await documentAPI.reject(selected.id, reason); setSelected(null); setReason(''); await load(); } catch (apiError) { setError(apiError.message || 'Unable to reject document.'); } };
  const columns = [{ header: 'Doc ID', accessor: 'id' }, { header: 'Beneficiary', accessor: 'beneficiary', cell: value => beneficiaries.find(item => item.id === value)?.name || value || 'N/A' }, { header: 'Document', accessor: 'file_name' }, { header: 'Type', accessor: 'document_type' }, { header: 'Uploaded', accessor: 'uploaded_at', cell: value => new Date(value).toLocaleDateString() }, { header: 'Status', accessor: 'verification_status', cell: value => <Badge variant={value === 'VERIFIED' ? 'success' : value === 'REJECTED' ? 'error' : 'warning'}>{value}</Badge> }, { header: 'Verified By', accessor: 'verified_by', cell: value => value || 'Pending' }, { header: 'Verified At', accessor: 'verified_at', cell: value => value ? new Date(value).toLocaleDateString() : 'N/A' }, { header: 'Rejection Reason', accessor: 'rejection_reason', cell: value => value || 'N/A' }, { header: 'Actions', accessor: 'id', cell: (_, row) => row.verification_status === 'PENDING' ? <div className="flex gap-2"><button onClick={() => verify(row.id)} className="text-green-600" title="Verify"><CheckCircle className="h-5 w-5" /></button><button onClick={() => setSelected(row)} className="text-red-600" title="Reject"><XCircle className="h-5 w-5" /></button></div> : <span className="text-xs text-gray-500">Processed</span> }];
  return <div className="space-y-6"><PageHeader title="Document Verification" subtitle="Upload supporting documents and review verification status" />{error && <div className="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}<div className="bg-white rounded-xl border border-gray-200 shadow-sm p-5"><div className="flex items-center gap-2 mb-4"><UploadCloud className="w-5 h-5 text-teal-600" /><h2 className="text-lg font-bold">Upload Document</h2></div><form onSubmit={upload} className="grid grid-cols-1 md:grid-cols-3 gap-4 items-start"><FormSelect label="Beneficiary" name="beneficiary" value={beneficiary} onChange={event => setBeneficiary(event.target.value)} options={beneficiaries.map(item => ({ value: item.id, label: `${item.name} (${item.beneficiary_id})` }))} placeholder="Select beneficiary" required /><FormSelect label="Document Type" name="document_type" value={documentType} onChange={event => setDocumentType(event.target.value)} options={documentTypes} required /><div><FileUpload label="File" accept=".pdf,.jpg,.jpeg,.png" onFileSelect={selectFile} currentFile={file} error={uploadError} /><button disabled={uploading} className="w-full bg-teal-600 text-white px-4 py-2 rounded-md text-sm font-medium disabled:opacity-50">{uploading ? 'Uploading...' : 'Upload Document'}</button></div></form></div><DataTable columns={columns} data={documents} keyField="id" loading={loading} emptyMessage="No documents found." /><Modal isOpen={Boolean(selected)} onClose={() => setSelected(null)} title="Reject Document"><div className="space-y-4"><textarea value={reason} onChange={event => setReason(event.target.value)} placeholder="Reason for rejection" className="w-full rounded-md border border-gray-300 p-2" rows="4" /><div className="flex justify-end gap-2"><button onClick={() => setSelected(null)} className="px-4 py-2 border rounded-md text-sm">Cancel</button><button disabled={!reason.trim()} onClick={reject} className="px-4 py-2 bg-red-600 text-white rounded-md text-sm">Reject</button></div></div></Modal></div>;
}
