# Generated by Django 5.1.15 on 2026-09-27 07:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('family_size', models.IntegerField()),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('income_frequency', models.CharField(max_length=50)),
                ('housing_condition', models.CharField(choices=[('PUCCA', 'Pucca'), ('SEMI_PUCCA', 'Semi Pucca'), ('KUTCHA', 'Kutcha'), ('HOMELESS', 'Homeless')], max_length=20)),
                ('num_earning_members', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=20)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('city_village', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified'), ('ASSESSED', 'Assessed')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiaries.family')),
            ],
        ),
        migrations.CreateModel(
            name='EducationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, max_length=255)),
                ('grade', models.CharField(blank=True, max_length=50)),
                ('academic_year', models.CharField(blank=True, max_length=20)),
                ('education_level', models.CharField(choices=[('PRIMARY', 'Primary'), ('UPPER_PRIMARY', 'Upper Primary'), ('SECONDARY', 'Secondary'), ('HIGHER_SECONDARY', 'Higher Secondary'), ('GRADUATE', 'Graduate'), ('DROPOUT', 'Dropout'), ('NEVER_ENROLLED', 'Never Enrolled')], max_length=50)),
                ('enrollment_status', models.CharField(choices=[('ENROLLED', 'Enrolled'), ('DROPPED_OUT', 'Dropped Out'), ('NEVER_ENROLLED', 'Never Enrolled'), ('GRADUATED', 'Graduated')], max_length=50)),
                ('academic_performance', models.CharField(blank=True, choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('AVERAGE', 'Average'), ('BELOW_AVERAGE', 'Below Average'), ('POOR', 'Poor')], max_length=50)),
                ('attendance_percentage', models.FloatField(blank=True, null=True)),
                ('educational_difficulties', models.TextField(blank=True)),
                ('higher_education_interest', models.BooleanField(default=False)),
                ('beneficiary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='beneficiaries.beneficiary')),
            ],
        ),
        migrations.CreateModel(
            name='ParentGuardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('relationship', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('employment_status', models.CharField(choices=[('EMPLOYED_GOVT', 'Employed Govt'), ('EMPLOYED_PRIVATE', 'Employed Private'), ('SELF_EMPLOYED', 'Self Employed'), ('DAILY_WAGE', 'Daily Wage'), ('UNEMPLOYED', 'Unemployed'), ('RETIRED', 'Retired'), ('DISABLED', 'Disabled')], max_length=50)),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_primary_guardian', models.BooleanField(default=False)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='beneficiaries.family')),
            ],
        ),
        migrations.CreateModel(
            name='RationCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_ration_card', models.BooleanField()),
                ('category', models.CharField(choices=[('AAY', 'AAY'), ('PHH', 'PHH'), ('NPHH', 'NPHH'), ('APL', 'APL'), ('BPL', 'BPL'), ('ANTYODAYA', 'Antyodaya'), ('NONE', 'None')], max_length=20)),
                ('card_number', models.CharField(blank=True, max_length=100)),
                ('verification_status', models.CharField(default='PENDING', max_length=20)),
                ('family', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='beneficiaries.family')),
            ],
        ),
        migrations.CreateModel(
            name='SocioEconomicDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_electricity', models.BooleanField()),
                ('has_clean_water', models.BooleanField()),
                ('has_toilet', models.BooleanField()),
                ('meals_per_day', models.IntegerField()),
                ('has_health_insurance', models.BooleanField()),
                ('distance_to_school_km', models.FloatField()),
                ('additional_notes', models.TextField(blank=True)),
                ('beneficiary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='socioeconomic', to='beneficiaries.beneficiary')),
            ],
        ),
    ]
