# Generated by Django 5.1.15 on 2026-09-27 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('beneficiaries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('scheme_type', models.CharField(max_length=50)),
                ('education_level_min', models.CharField(blank=True, max_length=50)),
                ('education_level_max', models.CharField(blank=True, max_length=50)),
                ('min_age', models.IntegerField(blank=True, null=True)),
                ('max_age', models.IntegerField(blank=True, null=True)),
                ('income_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ration_card_required', models.BooleanField(default=False)),
                ('accepted_ration_categories', models.JSONField(default=list)),
                ('gender_requirement', models.CharField(default='ANY', max_length=20)),
                ('benefits', models.TextField()),
                ('required_documents', models.JSONField(default=list)),
                ('application_method', models.CharField(blank=True, max_length=255)),
                ('official_url', models.URLField(blank=True)),
                ('official_source', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_demo_data', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchemeEligibilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100)),
                ('operator', models.CharField(max_length=10)),
                ('value', models.JSONField()),
                ('description', models.TextField()),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='schemes.governmentscheme')),
            ],
        ),
        migrations.CreateModel(
            name='SchemeRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ELIGIBLE', 'Eligible'), ('POTENTIALLY_ELIGIBLE', 'Potentially Eligible'), ('NOT_ELIGIBLE', 'Not Eligible'), ('INSUFFICIENT_INFO', 'Insufficient Info')], max_length=50)),
                ('match_percentage', models.FloatField()),
                ('matched_criteria', models.JSONField(default=dict)),
                ('unmatched_criteria', models.JSONField(default=dict)),
                ('missing_info', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessments.assessment')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiaries.beneficiary')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schemes.governmentscheme')),
            ],
        ),
        migrations.CreateModel(
            name='SupportApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RECOMMENDED', 'Recommended'), ('DOCUMENTS_PENDING', 'Documents Pending'), ('APPLICATION_STARTED', 'Application Started'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUPPORT_PROVIDED', 'Support Provided')], max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schemes.schemerecommendation')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='schemes.supportapplication')),
            ],
        ),
    ]
