import React, { useEffect, useState } from 'react';
import PageHeader from '../../components/common/PageHeader';
import DataTable from '../../components/common/DataTable';
import Badge from '../../components/common/Badge';
import Modal from '../../components/common/Modal';
import FormInput from '../../components/forms/FormInput';
import FormTextarea from '../../components/forms/FormTextarea';
import FormSelect from '../../components/forms/FormSelect';
import { ruleAPI } from '../../services/api';
import { Edit, Plus } from 'lucide-react';

const emptyRule = { category_id: '', name: '', description: '', factor: 'MONTHLY_INCOME', operator: 'LT', threshold_value: '', score: 10, priority: 1, is_active: true };
const operators = ['LT', 'LTE', 'GT', 'GTE', 'EQ', 'NEQ', 'IN', 'NOT_IN', 'BETWEEN'];

export default function RuleManagement() {
  const [rules, setRules] = useState([]); const [categories, setCategories] = useState([]); const [form, setForm] = useState(emptyRule); const [editing, setEditing] = useState(null); const [modalOpen, setModalOpen] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const load = () => ruleAPI.list().then(setRules).catch(apiError => setError(apiError.message || 'Unable to load rules.')).finally(() => setLoading(false)); useEffect(() => { load(); ruleAPI.categories().then(setCategories).catch(apiError => setError(apiError.message || 'Unable to load rule categories.')); }, []);
  const update = event => setForm(previous => ({ ...previous, [event.target.name]: event.target.value }));
  const openCreate = () => { setEditing(null); setForm({ ...emptyRule, category_id: categories[0]?.id || '' }); setModalOpen(true); };
  const openEdit = rule => { setEditing(rule.id); setForm({ ...emptyRule, ...rule, category_id: rule.category?.id || '', threshold_value: typeof rule.threshold_value === 'string' ? rule.threshold_value : JSON.stringify(rule.threshold_value) }); setModalOpen(true); };
  const save = async event => { event.preventDefault(); setSaving(true); setError(''); let threshold; try { threshold = JSON.parse(form.threshold_value); } catch { threshold = form.threshold_value; } const payload = { category_id: Number(form.category_id), name: form.name, description: form.description, factor: form.factor, operator: form.operator, threshold_value: threshold, score: Number(form.score), priority: Number(form.priority), is_active: form.is_active }; try { if (editing) await ruleAPI.update(editing, payload); else await ruleAPI.create(payload); setModalOpen(false); setNotice(editing ? 'Rule updated.' : 'Rule created.'); load(); } catch (apiError) { setError(apiError.message || 'Unable to save rule.'); } finally { setSaving(false); } };
  const toggle = async rule => { try { await ruleAPI.toggleActive(rule.id, !rule.is_active); setNotice(`Rule ${rule.is_active ? 'disabled' : 'activated'}.`); load(); } catch (apiError) { setError(apiError.message || 'Unable to update rule.'); } };
  const columns = [{ header: 'ID', accessor: 'id' }, { header: 'Rule', accessor: 'name' }, { header: 'Category', accessor: 'category', cell: value => value?.name || 'N/A' }, { header: 'Condition', accessor: 'factor', cell: (_, row) => `${row.factor} ${row.operator} ${JSON.stringify(row.threshold_value)}` }, { header: 'Score', accessor: 'score' }, { header: 'Status', accessor: 'is_active', cell: value => <Badge variant={value ? 'success' : 'error'}>{value ? 'Active' : 'Inactive'}</Badge> }, { header: 'Actions', accessor: 'id', cell: (_, row) => <div className="flex gap-2"><button onClick={() => openEdit(row)} className="text-teal-600" title="Edit"><Edit className="h-4 w-4" /></button><button onClick={() => toggle(row)} className="text-amber-600 text-xs">{row.is_active ? 'Disable' : 'Enable'}</button></div> }];
  return <div><PageHeader title="Rule Management" subtitle="Backend rule categories and vulnerability thresholds" actions={[{ label: 'Add Rule', icon: Plus, variant: 'primary', onClick: openCreate }]} />{error && <div className="mb-4 text-sm text-red-700">{error}</div>}{notice && <div className="mb-4 rounded-lg border border-teal-200 bg-teal-50 px-4 py-3 text-sm text-teal-800">{notice}</div>}<DataTable columns={columns} data={rules} keyField="id" loading={loading} emptyMessage="No rules configured." /><Modal isOpen={modalOpen} onClose={() => setModalOpen(false)} title={editing ? 'Edit Rule' : 'Add Rule'}><form onSubmit={save} className="space-y-3"><FormSelect label="Category" name="category_id" value={form.category_id} onChange={update} options={categories.map(category => ({ value: category.id, label: category.name }))} required /><FormInput label="Rule Name" name="name" value={form.name} onChange={update} required /><FormTextarea label="Description" name="description" value={form.description} onChange={update} required /><FormInput label="Factor" name="factor" value={form.factor} onChange={update} required /><FormSelect label="Operator" name="operator" value={form.operator} onChange={update} options={operators} required /><FormInput label="Threshold / JSON value" name="threshold_value" value={form.threshold_value} onChange={update} required /><div className="grid grid-cols-2 gap-3"><FormInput label="Score" name="score" type="number" value={form.score} onChange={update} required /><FormInput label="Priority" name="priority" type="number" value={form.priority} onChange={update} required /></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="is_active" checked={form.is_active} onChange={event => setForm(previous => ({ ...previous, is_active: event.target.checked }))} /> Active</label><div className="flex justify-end gap-2 pt-3"><button type="button" onClick={() => setModalOpen(false)} className="px-4 py-2 border rounded-md text-sm">Cancel</button><button disabled={saving} className="px-4 py-2 bg-teal-600 text-white rounded-md text-sm">{saving ? 'Saving...' : 'Save Rule'}</button></div></form></Modal></div>;
}
