import React, { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import PageHeader from '../../components/common/PageHeader';
import { schemeAPI } from '../../services/api';
import { Filter, Search } from 'lucide-react';

export default function SchemeList() {
  const [schemes, setSchemes] = useState([]); const [searchTerm, setSearchTerm] = useState(''); const [typeFilter, setTypeFilter] = useState('ALL'); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { schemeAPI.list().then(setSchemes).catch(apiError => setError(apiError.message || 'Unable to load schemes.')).finally(() => setLoading(false)); }, []);
  const filtered = useMemo(() => schemes.filter(scheme => (!searchTerm || `${scheme.name} ${scheme.department}`.toLowerCase().includes(searchTerm.toLowerCase())) && (typeFilter === 'ALL' || scheme.scheme_type === typeFilter)), [schemes, searchTerm, typeFilter]);
  return <div className="space-y-6"><PageHeader title="Government Education & Welfare Schemes" subtitle="Repository of active government support programs" />{error && <div className="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}{loading && <div className="text-sm text-gray-500">Loading schemes...</div>}<div className="bg-white p-4 rounded-xl border border-gray-200 shadow-sm flex flex-col sm:flex-row gap-4 justify-between"><div className="relative w-full sm:w-80"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" /><input className="w-full pl-9 pr-4 py-2 text-sm border border-gray-300 rounded-lg" placeholder="Search schemes or ministry..." value={searchTerm} onChange={e => setSearchTerm(e.target.value)} /></div><div className="flex items-center gap-2"><Filter className="w-4 h-4 text-gray-400" /><select value={typeFilter} onChange={e => setTypeFilter(e.target.value)} className="text-sm border border-gray-300 rounded-lg px-3 py-2"><option value="ALL">All Scheme Types</option>{[...new Set(schemes.map(s => s.scheme_type))].map(type => <option key={type} value={type}>{type}</option>)}</select></div></div><div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">{filtered.map(scheme => <div key={scheme.id} className="bg-white rounded-xl shadow-sm border border-gray-200 p-6 flex flex-col justify-between"><div><span className="text-xs font-bold px-2.5 py-0.5 rounded-full bg-teal-100 text-teal-800">{scheme.scheme_type?.replaceAll('_', ' ')}</span><h3 className="text-lg font-bold text-gray-900 mt-3">{scheme.name}</h3><p className="text-xs font-medium text-teal-700 mb-3">{scheme.department}</p><p className="text-xs text-gray-600 line-clamp-3">{scheme.description}</p><div className="mt-4 text-xs text-gray-600">Income limit: {scheme.income_limit ? `₹${Number(scheme.income_limit).toLocaleString()}/mo` : 'No limit'}</div></div><div className="pt-4 mt-4 border-t border-gray-100 flex justify-end"><Link to={`/schemes/${scheme.id}`} className="text-sm font-semibold text-teal-600">View Details →</Link></div></div>)}{!loading && !filtered.length && <div className="col-span-full text-sm text-gray-500">No schemes found.</div>}</div></div>;
}
